FROM geebuild:v1 AS base

WORKDIR /

COPY entrypoint.sh /entrypoint.sh

WORKDIR /opt/myapp/earthenterprise/earth_enterprise/src/installer

RUN apt-get update &&\
	apt-get install --no-install-recommends python-pil\
	python-tornado

# Install earth server
RUN echo 'C\ny' | bash install_server.sh

#RUN rm -frd /opt/myapp/earthenterprise\
	usr/lib/ogdi

#RUN rm -frd /tmp
#RUN rm -frd /usr/bin
#RUN rm -frd /usr/include
#RUN rm -frd /usr/share
#RUN rm -frd /usr/sbin
#RUN rm -frd /usr/local
#RUN rm -frd /usr/games

#RUN apt-get -y --purge remove scons\
#	systemd\
#	python2.7\
#	python3\
#	python3.5
	

FROM ubuntu:16.04
#COPY --from=base / /
COPY --from=base /etc /etc
COPY --from=base /bin /bin
COPY --from=base /entrypoint.sh /
#COPY --from=base /opt/google/gehttpd/bin /opt/google/gehttpd/bin
#COPY --from=base /opt/google /opt/google
#COPY --from=base /var/opt/google /var/opt/google
#COPY --from=base /usr /usr

EXPOSE 80

ENTRYPOINT ["bash", "/entrypoint.sh"]
