FROM geebuild:v1 AS base

# Download xserver package
RUN apt-get update &&\
	apt-get -y install --no-install-recommends x11-xserver-utils

WORKDIR /

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh

WORKDIR /opt/myapp/earthenterprise/earth_enterprise/src/installer

# Install fusion
RUN echo C | bash install_fusion.sh

# Copy tutorial script
RUN cp /opt/myapp/earthenterprise/earth_enterprise/tutorial/FusionTutorial/download_tutorial.sh /download_tutorial.sh

# Remove build files
RUN rm -frd /opt/myapp/earthenterprise

# Remove server files
RUN rm -frd /tmp/fusion_os_install

FROM alpine
COPY --from=base / /

# Set entrypoint
ENTRYPOINT ["bash", "/entrypoint.sh"]
