FROM geebuild:v1

WORKDIR earthenterprise/earth_enterprise/tutorial

RUN apt-get update &&\
	apt-get install --no-install-recommends wget

#RUN wget http://data.opengee.org/FusionTutorial-Full.tar.gz
RUN wget https://opengee-dev.s3.amazonaws.com/FusionTutorial-Full.tar.gz

RUN mkdir FusionTutorial

RUN tar -xvzf FusionTutorial-Full.tar.gz -C FusionTutorial

WORKDIR /opt/google/share/tutorials/fusion

RUN bash download_tutorial.sh
